### PR TITLE
Support computing features for whisper

### PR DESCRIPTION
**Pull request by csukuangfj**
# Usage
```python3

import torchaudio
import torch
import kaldifeat

def compute_features(filename: str) -> torch.Tensor:
    """
    Args:
      filename:
        Path to an audio file.
    Returns:
      Return a 1-D float32 tensor of shape (1, 80, 3000) containing the features.
    """
    wave, sample_rate = torchaudio.load(filename)
    audio = wave[0].contiguous()  # only use the first channel
    if sample_rate != 16000:
        audio = torchaudio.functional.resample(
            audio, orig_freq=sample_rate, new_freq=16000
        )

    opts = kaldifeat.WhisperFbankOptions(device="cpu")
    whisper_fbank = kaldifeat.WhisperFbank(opts)
    features = whisper_fbank(audio)  # [num_frames, 80]

    # we need to pad it to [3000, 80]
    pad = 3000 - features.shape[0]
    if pad > 0:
        features = torch.nn.functional.pad(features, (0, 0, 0, pad), "constant", 0)
    else:
        features = features[:3000]

    features = features.t()
    # now features is [80, 3000]
    return features.unsqueeze(0)  # [1, 80, 3000]
```

### CODE REVIEW

**Comment by HuangJian2024** [comment]
when running test_whisper_fbank.py, the results of kaldifeat and ground truth(whisper) are not same. Are there any differences?

**Comment by csukuangfj** [comment]
It handles the edges differently, but the difference should be minor.

If you can find a wav that produces different recognition results due to using kaldifeat, please send us the wav.

**Comment by HuangJian2024** [comment]
> recognition

Firstly, the shape is not same. The result of kalidfeat is two frames less. Secondly, the difference of the value is 10-2. Is there some methods to aligh the results？

**Comment by csukuangfj** [comment]
> It handles the edges differently, but the difference should be minor.
> 
> If you can find a wav that produces different recognition results due to using kaldifeat, please send us the wav.

Please have a look at this comment.

**Pull request merged**
